CREATE USER user1_homework1 WITH PASSWORD '123';
CREATE USER user2_homework1 WITH PASSWORD '123';
ALTER USER user1_homework1 WITH SUPERUSER;
ALTER USER user1_homework1 WITH CREATEDB CREATEROLE REPLICATION;
GRANT SELECT, UPDATE ON ALL TABLES IN SCHEMA PUBLIC TO user2_homework1;
\du
\q
CREATE DATABASE database1_homework1;
\l
\q
ALTER ROLE user1_homework1 WITH PASSWORD '111';
ALTER ROLE user2_homework1 WITH PASSWORD '222';


