version: "3"
services:
    frontend:
        image: client
        ports:
          - "3000:3000"
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        # volumes:
        #     - ./client:/app
        environment:
            REACT_APP_API_URL: 'http://localhost:5000'
            # REACT_APP_API_URL: ${REACT_APP_API_URL}
    backend:
        image: server
        ports:
          - "5000:5000"
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        # volumes:
        #     - ./server:/app
        depends_on: 
            - postgres
        environment:
            PORT: 5000
            PG_USERNAME: examen1
            PG_HOST: 127.0.0.1
            PG_DATABASE: examen_db1
            PG_PASSWORD: 123
            PG_PORT: 5432
            JWT_SECRET: my_jwt_secret
            CLIENT_URL: http://localhost:3000
    postgres:
        image: postgres
        ports:
            - "127.0.0.1:5433:5432"
        environment:
            POSTGRES_USER: examen1
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: examen_db1

